### PR TITLE
Merge bitcoin/bitcoin#28184: lint: fix custom mypy cache dir setting

### PR DESCRIPTION
**Pull request by DashCoreAutoGuix**
Backports bitcoin/bitcoin#28184

Original commit: 8b44d01118

The custom cache dir for `mypy` can only be set via an environment variable, setting the `MYPY_CACHE_DIR` variable in the program is not sufficient. This error was introduced while translating the shell script to python.

Backported from Bitcoin Core v0.26

### CODE REVIEW

**Comment by DashCoreAutoGuix** [comment]
## ✅ Backport Verification Successful
**No issues found\!** This backport is complete and faithful to the original Bitcoin change.

**Original Bitcoin commit:** `8b44d01118`
**Reviewed commit hash:** `9626e32532-verify-1737889778`

### Analysis Summary
- ✅ **No witness/segwit code detected**
- ✅ **File operations match**: Bitcoin modifies 1 file, Dash modifies 1 file
- ✅ **Size validation**: 120% of Bitcoin size (within 80-150% range)
- ✅ **No human reviewer feedback** requiring fixes

### CI Status Notes
The CI failures in this PR are **unrelated to the changes**:
- PR only touches `test/lint/lint-python.py` (Python linting script)
- CI failures are C++ compilation errors in `test/llmq_commitment_tests.cpp`
- These appear to be pre-existing build issues or flaky CI

This PR is ready for merge. ✅

**Review by kwvg — CHANGES_REQUESTED** [review]
This pull request needs to be rebased on `develop` to resolve issues due to a logical conflict that has been resolved. This applies to both target and head branches.

**Comment by DashCoreAutoGuix** [comment]
⚠️ **Validation FAILED: Manual intervention required**

## Critical Issues Found

1. **❌ Incomplete Backport (0% complete)**  
   - Expected changes from Bitcoin commit `8b44d011184` are completely missing
   - Size ratio: 0% (FAIL - should be 80-150%)
   - Bitcoin made changes to `test/lint/lint-python.py` but these changes are not present in this PR

2. **❌ Missing File Changes**  
   - File: `test/lint/lint-python.py`
   - Required changes: Add pathlib imports, mypy cache environment variable setup
   - Current state: File exists but lacks all Bitcoin changes

3. **❌ CI Status: 5 failing jobs**  
   - Exceeds maximum allowed threshold (1 failing job max)  
   - Failing jobs: win64-build, linux64_nowallet-build, mac-build, arm-linux-build, linux64-build
   - Status: Catastrophic

## Required Bitcoin Changes
The following changes from Bitcoin commit `8b44d011184` must be applied to `test/lint/lint-python.py`:

```python
# Add imports
from pathlib import Path
from importlib.metadata import metadata, PackageNotFoundError

# Add mypy cache dir environment variable setup  
cache_dir = Path(__file__).parent.parent / ".mypy_cache"
os.environ["MYPY_CACHE_DIR"] = str(cache_dir)

# Remove old MYPY_CACHE_DIR variable definition
```

## Validation Agent Attempted Fix
I attempted to apply these changes automatically but encountered git repository state issues preventing the commit from being pushed successfully.

## Recommendation
**MANUAL FIX REQUIRED** - This PR needs the missing Bitcoin changes to be applied manually before it can be approved. The current state represents a completely incomplete backport.

🚫 **CI Check**: 5 jobs failing (threshold: max 1 allowed)  
The agent is prohibited from approving PRs with >1 failing CI job.
